<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-04-19T06:42:04+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
