<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-04-19T16:15:15+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1492584133,
        'latest_version' => '8.1.0',
        'do_page_reindex_check' => false,
    ],
];
