<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-04-19T06:40:04+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'It\'s over easy',
        ],
    ],
];
